### ISSUE TITLE
ubuntu 22.04lts系统环境下 ，即使已经安装gcc9并设为高优先级，依旧与gcc12报错一样

### ISSUE THREAD

**Issue by Siverse** [coolsnowwolf/openwrt-gl-ax1800#18]
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[7]: *** [scripts/Makefile.host:116: scripts/dtc/dtc] Error 1
make[6]: *** [scripts/Makefile.build:573: scripts/dtc] Error 2
make[6]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
make[5]: *** [Makefile:557: scripts] Error 2
make[5]: Leaving directory '/home/siverse/v6firm/openwrt-gl-ax1800/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60'
make[4]: *** [Makefile:24: /home/siverse/v6firm/openwrt-gl-ax1800/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60/.modules] Error 2
make[4]: Leaving directory '/home/siverse/v6firm/openwrt-gl-ax1800/target/linux/ipq60xx'
make[3]: *** [Makefile:13: compile] Error 2
make[3]: Leaving directory '/home/siverse/v6firm/openwrt-gl-ax1800/target/linux'
time: target/linux/compile#1.58#0.29#1.19
make[2]: *** [target/Makefile:25: target/linux/compile] Error 2
make[2]: Leaving directory '/home/siverse/v6firm/openwrt-gl-ax1800'
make[1]: *** [target/Makefile:18: /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/siverse/v6firm/openwrt-gl-ax1800'
make: *** [/home/siverse/v6firm/openwrt-gl-ax1800/include/toplevel.mk:227：world] 错误 2

**Comment by coolsnowwolf** [comment]
已修复
