### ISSUE TITLE
无法用web刷固件

### ISSUE THREAD

**Issue by thankeyes** [coolsnowwolf/openwrt-gl-ax1800#19]
刷了编译的固件后,无法用web刷固件了,只能捅屁股从uboot里刷

**Comment by aiamadeus** [comment]
？你就不能描述详细一点？让我们算命是吧

**Comment by thankeyes** [comment]
抱歉,没写清楚
路由器是ZN-M2,刷了用源代码编译出来的固件后,就不能在web那刷其他固件了
也没显示错误,web刷机会自动重启,但重启后系统没有任何变化

我还试验了IPQ WRT 固件支持群里的openwrt-ipq60xx-R22.5.25-zn_m2-squashfs-nand-sysupgrade.rar
也是刷完后,就无法从web刷其他固件了

只能从uboot里刷机

**Comment by aiamadeus** [comment]
你只能这里编译出来的刷这里的，其它地方的固件可能 board_name 或者 ubi layout 不一样。
