### ISSUE TITLE
mr7350 无法从 uboot 刷机

### ISSUE THREAD

**Issue by seanlook** [coolsnowwolf/openwrt-gl-ax1800#20]
请教下，我的是 linksys mr73350，用这个仓库自己编译后，刷入成功

在这里 [coolsnowwolf](https://mianbaoduo.com/o/bread/mbd-YpmYm5tv) MR7350_MIBIB_UBOOT.zip 付费了不死 uboot，并刷进了分区。开机能进入 uboot firmware upgrade 页面，但是继续选 op 的 factory 来刷，路由再也无法正常启动，选 mr7350 官方固件，也同样，无法打开路由器页面，怀疑是无法进入系统，试过异常断电，也不行。（但是可以反复reset 进入 firmware upgrade 页）

不确定是不是 uboot 问题，求帮助，感谢感谢~

**Comment by aiamadeus** [comment]
对于领势的机子，只支持原厂分区刷入。

**Comment by seanlook** [comment]
我从这里[FW_MR7350_1.1.7.209317_prod.img](https://www.linksys.com/support-article?articleNum=316813) 下载了 mr7350的原厂固件，刷进去路由器也无法启动呢

**Comment by aiamadeus** [comment]
你改了分区和 uboot 当然无法启动。
