### ISSUE TITLE
希望能增加mr7350plus版本

### ISSUE THREAD

**Issue by zjwxh** [coolsnowwolf/openwrt-gl-ax1800#25]
希望雕大能增加mr7350plus版本，mr7350编译的固件没法刷入到plus大分区版本，谢谢了。

**Comment by WowRouter** [comment]
所谓的plus版本，小圈子玩玩得了，刷机没后路了。官方默认分区双系统更好用，而且还能随时刷回原厂。

**Comment by zjwxh** [comment]
是啊，很后悔刷了大分区plus版本，现在刷回官方双系统也不知道咋搞

**Comment by asushugo** [comment]
谁说不能刷回原厂的？

**Comment by zjwxh** [comment]
指点一下，如何刷回原厂，谢谢
