### ISSUE TITLE
360v6  固件编译失败 日志如下

### ISSUE THREAD

**Issue by Siverse** [coolsnowwolf/openwrt-gl-ax1800#27]
SHELL= flock /home/siverse/v6firm/openwrt-gl-ax1800/tmp/.root-copy.flock -c 'cp -fpR /home/siverse/v6firm/openwrt-gl-ax1800/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/packages/.pkgdir/kmod-usb3/. /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/root-ipq60xx/'
touch /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/root-ipq60xx/stamp/.kmod-usb3_installed
echo "kmod-usb3" >> /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux.default.install
mkdir -p /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/root-ipq60xx/stamp

SHELL= flock /home/siverse/v6firm/openwrt-gl-ax1800/tmp/.root-copy.flock -c 'cp -fpR /home/siverse/v6firm/openwrt-gl-ax1800/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/packages/.pkgdir/kmod-usb-phy-msm/. /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/root-ipq60xx/'
touch /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/root-ipq60xx/stamp/.kmod-usb-phy-msm_installed
echo "kmod-usb-phy-msm" >> /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux.default.install
make[3]: Leaving directory '/home/siverse/v6firm/openwrt-gl-ax1800/package/kernel/linux'
time: package/kernel/linux/compile#7.62#1.68#8.21
make[2]: Leaving directory '/home/siverse/v6firm/openwrt-gl-ax1800'
make[1]: *** [package/Makefile:107: /home/siverse/v6firm/openwrt-gl-ax1800/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/siverse/v6firm/openwrt-gl-ax1800'
make: *** [/home/siverse/v6firm/openwrt-gl-ax1800/include/toplevel.mk:227：world] 错误 2

**Comment by aiamadeus** [comment]
你的具体编译日志呢
