### ISSUE TITLE
kernel-headers 下载校验不通过

### ISSUE THREAD

**Issue by CWZ7605** [coolsnowwolf/openwrt-gl-ax1800#3]
![图片](https://user-images.githubusercontent.com/4016785/160189714-35ce9890-1538-4aac-8bf8-9e6980aa3e7d.png)

我手动下载文件放置在dl中后，再运行，会提示patch-4.4失败。

**Comment by AmadeusGhost** [comment]
手动下载上游的内核肯定不行的，要用 dl 里面的那个。

**Comment by CWZ7605** [comment]
我改了"./include/kernel-version.mk"里面内核的hash值，改成了ee98e905ae1a9d285cd1fee2d4c94f4dc0623ef477ce7762f14f181c52aa20a3，现在继续编译了
