### ISSUE TITLE
编译btrfs模块出错，能否修复，谢谢

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/openwrt-gl-ax1800#30]
环境：
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

lsb_release -ra
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

具体错误日志如下：
fs/btrfs/volumes.c:111:11: error: duplicate 'const' declaration specifier [-Werror=duplicate-decl-specifier]
 const u64 const btrfs_raid_group[BTRFS_NR_RAID_TYPES] = {
           ^~~~~
cc1: all warnings being treated as errors
make[7]: *** [fs/btrfs/volumes.o] Error 1
scripts/Makefile.build:337: recipe for target 'fs/btrfs/volumes.o' failed
scripts/Makefile.build:573: recipe for target 'fs/btrfs' failed
make[6]: *** [fs/btrfs] Error 2
make[5]: *** [fs] Error 2
Makefile:971: recipe for target 'fs' failed
make[5]: Leaving directory '/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60'
make[4]: *** [/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60/.modules] Error 2
Makefile:23: recipe for target '/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60/.modules' failed
make[4]: Leaving directory '/openwrt/target/linux/ipq60xx'
make[3]: *** [compile] Error 2
Makefile:13: recipe for target 'compile' failed
make[3]: Leaving directory '/openwrt/target/linux'
time: target/linux/compile#31.96#8.38#65.77
make[2]: *** [target/linux/compile] Error 2
target/Makefile:23: recipe for target 'target/linux/compile' failed

另外：xfs ksmbd这2个文件系统模块也是类似错误

**Comment by paldier** [comment]
源代码错误，不能双const，目测是musl祖传问题
