### ISSUE TITLE
dm、scsi驱动模块编译出错

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/openwrt-gl-ax1800#31]
环境：
lsb_release -ra
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

A 正常编译的配置增加scsi模块后
diff 6000-OpenWrt-AX5-AX1800-zsfd-next-3-luci-3.config .config 
< # CONFIG_PACKAGE_kmod-scsi-generic is not set
< # CONFIG_PACKAGE_kmod-scsi-tape is not set
> CONFIG_PACKAGE_kmod-scsi-generic=m
> CONFIG_PACKAGE_kmod-scsi-tape=m

错误如下：
drivers/scsi/st.c: In function 'create_one_cdev':
drivers/scsi/st.c:4097:24: error: '%s' directive output may be truncated writing up to 31 bytes into a region of size between 9 and 10 [-Werror=format-truncation=]
  snprintf(name, 10, "%s%s%s", rew ? "n" : "",
                        ^~
drivers/scsi/st.c:4097:2: note: 'snprintf' output 1 or more bytes (assuming 33) into a destination of size 10
  snprintf(name, 10, "%s%s%s", rew ? "n" : "",
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    tape->disk->disk_name, st_formats[i]);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [drivers/scsi/st.o] Error 1
scripts/Makefile.build:343: recipe for target 'drivers/scsi/st.o' failed
make[6]: *** [drivers/scsi] Error 2
scripts/Makefile.build:573: recipe for target 'drivers/scsi' failed
make[5]: *** [drivers] Error 2
Makefile:971: recipe for target 'drivers' failed

B 同样增加dax dm模块后
diff 6000-OpenWrt-AX5-AX1800-zsfd-next-3-luci-3.config .config

< # CONFIG_PACKAGE_kmod-dax is not set
< # CONFIG_PACKAGE_kmod-dm is not set
> CONFIG_PACKAGE_kmod-dax=m
> CONFIG_PACKAGE_kmod-dm=m
错误如下：
drivers/crypto/msm/ice.c:1503:5: error: redefinition of 'qcom_ice_setup_ice_hw'
 int qcom_ice_setup_ice_hw(const char *storage_type, int enable)
     ^~~~~~~~~~~~~~~~~~~~~
In file included from drivers/crypto/msm/ice.c:24:0:
include/crypto/ice.h:67:19: note: previous definition of 'qcom_ice_setup_ice_hw' was here
 static inline int qcom_ice_setup_ice_hw(const char *storage_type, int enable)
                   ^~~~~~~~~~~~~~~~~~~~~
make[8]: *** [drivers/crypto/msm/ice.o] Error 1
scripts/Makefile.build:343: recipe for target 'drivers/crypto/msm/ice.o' failed
make[7]: *** [drivers/crypto/msm] Error 2
scripts/Makefile.build:573: recipe for target 'drivers/crypto/msm' failed
make[6]: *** [drivers/crypto] Error 2
scripts/Makefile.build:573: recipe for target 'drivers/crypto' failed
make[5]: *** [drivers] Error 2
Makefile:971: recipe for target 'drivers' failed

**Comment by paldier** [comment]
加-Wno-format-truncation

**Comment by hzjnet** [comment]
> 加-Wno-format-truncation

谢谢 能详细点吗？ 尝试了drivers/scsi/st.c package/kernel/linux/modules/block.mk package/kernel/linux/Makefile都不行，谢谢
