### ISSUE TITLE
ipq6018: add support for yuncore ax840

### ISSUE THREAD

**Issue by legale** [coolsnowwolf/openwrt-gl-ax1800#32]
Hello. I'm trying to add support for yuncore ax840 
https://www.yuncorenet.com/item/ax840-p2-wi-fi6/11ax-1800mbps-wave2-0-high-power-industrial-ceiling-wireless-ap-wifi-6-ap

Based on this repo i'have made proper dts. Almost everything is good except wifi6 (only radio0 acn and radio1 bgn). I've found in my stock firmware that there is few packages for loading caldata.bin from spi flash. So i've added these packages to the sdk. Scripts for reading spi flash are working (caldata.bin appers in /lib/firmware/.../caldata.bin) but wifi6 is still not working. Maybe with your exp. you can say something.

This is stock fw bootlog:
https://paste.ec/paste/Q1AUMaYH#q4kdWmpTdTUJS7Gi1KLw3vcUnFyIPyHoDZnk8S2rCbe

This is fw maked with your sdk with some modifications (https://github.com/legale/openwrt-gl-ax1800):
https://zerobin.net/?557670cf61e29bc9#AqLzxEKGJWF+sPv2MHCde0Eh/Uqb0j/kMGnREnwciPg=

Thank you.

**Comment by aiamadeus** [comment]
You forget to change the following code: target/linux/ipq60xx/base-files.
