### ISSUE TITLE
crypto-qcrypto和sound-core 编译出错

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/openwrt-gl-ax1800#33]
环境：
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

lsb_release -ra
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

A 问题描述：
diff .config 6000-d220923-OpenWrt-AX5-AX1800-4-luci.config
1911c1911
< CONFIG_PACKAGE_kmod-crypto-qcrypto=m
CONFIG_PACKAGE_kmod-crypto-qcrypto is not set
在能正常编译的配置文件：6000-d220923-OpenWrt-AX5-AX1800-4-luci.config上增加crypto-qcrypto的编译选项出错

具体的出错log:
WARNING: modpost: Found 1 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
  GEN     .version
  CHK     include/generated/compile.h
  KSYM    .tmp_kallsyms1.o
  KSYM    .tmp_kallsyms2.o
  LD      vmlinux
  SORTEX  vmlinux
  SYSMAP  System.map
  OBJCOPY arch/arm64/boot/Image
  Building modules, stage 2.
  MODPOST 740 modules
WARNING: drivers/usb/dwc3/dwc3-qcom: 'msm_ep_unconfig' exported twice. Previous export was in drivers/usb/dwc3/dwc3-of-simple.ko
WARNING: drivers/usb/dwc3/dwc3-qcom: 'msm_ep_config' exported twice. Previous export was in drivers/usb/dwc3/dwc3-of-simple.ko
WARNING: drivers/usb/dwc3/dwc3-qcom: 'msm_dwc3_reset_dbm_ep' exported twice. Previous export was in drivers/usb/dwc3/dwc3-of-simple.ko
WARNING: drivers/usb/dwc3/dwc3-qcom: 'msm_data_fifo_config' exported twice. Previous export was in drivers/usb/dwc3/dwc3-of-simple.ko
ERROR: "qce_hw_support" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_open" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_enable_clk" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_disable_clk" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_process_sha_req" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_aead_req" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_ablk_cipher_req" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_get_driver_stats" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_clear_driver_stats" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_close" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_pm_table" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "compat_qcedev_ioctl" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_hw_support" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_open" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_close" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_disable_clk" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_enable_clk" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_process_sha_req" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_ablk_cipher_req" [drivers/crypto/msm/qcedev.ko] undefined!
make[6]: *** [__modpost] Error 1
scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[5]: *** [modules] Error 2
Makefile:1128: recipe for target 'modules' failed

B问题描述
在能正常编译的配置文件：6000-d220923-OpenWrt-AX5-AX1800-4-luci-2.config上增加声卡的编译选项出错
 diff .config 6000-d220923-OpenWrt-AX5-AX1800-4-luci-2.config
2069c2069
< CONFIG_PACKAGE_kmod-lib-crc32c=m
> CONFIG_PACKAGE_kmod-lib-crc32c=y

2434,2457c2434
< CONFIG_PACKAGE_kmod-sound-core=m
< CONFIG_PACKAGE_kmod-ac97=m
< CONFIG_PACKAGE_kmod-sound-dummy=m
< CONFIG_PACKAGE_kmod-sound-ens1371=m
< CONFIG_PACKAGE_kmod-sound-hda-core=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-analog=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-ca0110=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-ca0132=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-cirrus=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-cmedia=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-conexant=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-hdmi=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-idt=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-realtek=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-si3054=m
< CONFIG_PACKAGE_kmod-sound-hda-codec-via=m
< CONFIG_PACKAGE_kmod-sound-hda-intel=m
< CONFIG_PACKAGE_kmod-sound-i8x0=m
< CONFIG_PACKAGE_kmod-sound-mpu401=m
< CONFIG_PACKAGE_kmod-sound-seq=m
< CONFIG_PACKAGE_kmod-sound-soc-ac97=m
< CONFIG_PACKAGE_kmod-sound-soc-core=m
< CONFIG_PACKAGE_kmod-sound-via82xx=m
< CONFIG_PACKAGE_kmod-usb-audio=m
 CONFIG_PACKAGE_kmod-sound-core is not set

具体log如下：
HD Audio PCI (SND_HDA_INTEL) [M/n/?] m
Build hwdep interface for HD-audio driver (SND_HDA_HWDEP) [Y/n/?] y
Allow dynamic codec reconfiguration (SND_HDA_RECONFIG) [N/y/?] n
Support digital beep via input layer (SND_HDA_INPUT_BEEP) [N/y/?] n
Support initialization patch loading for HD-audio (SND_HDA_PATCH_LOADER) [N/y/?] n
Build Realtek HD-audio codec support (SND_HDA_CODEC_REALTEK) [M/n/?] m
Build Analog Device HD-audio codec support (SND_HDA_CODEC_ANALOG) [M/n/?] m
Build IDT/Sigmatel HD-audio codec support (SND_HDA_CODEC_SIGMATEL) [M/n/?] m
Build VIA HD-audio codec support (SND_HDA_CODEC_VIA) [M/n/?] m
Build HDMI/DisplayPort HD-audio codec support (SND_HDA_CODEC_HDMI) [M/n/?] m
Build Cirrus Logic codec support (SND_HDA_CODEC_CIRRUS) [M/n/?] m
Build Conexant HD-audio codec support (SND_HDA_CODEC_CONEXANT) [M/n/?] m
Build Creative CA0110-IBG codec support (SND_HDA_CODEC_CA0110) [M/n/?] m
Build Creative CA0132 codec support (SND_HDA_CODEC_CA0132) [M/n/?] m
  Support new DSP code for CA0132 codec (SND_HDA_CODEC_CA0132_DSP) [N/y/?] n
Build C-Media HD-audio codec support (SND_HDA_CODEC_CMEDIA) [M/n/?] m
Build Silicon Labs 3054 HD-modem codec support (SND_HDA_CODEC_SI3054) [M/n/?] m
Enable generic HD-audio codec parser (SND_HDA_GENERIC) [M/?] m
Default time-out for HD-audio power-save mode (SND_HDA_POWER_SAVE_DEFAULT) [0] (NEW) aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.

make[7]: *** [silentoldconfig] Error 1
scripts/kconfig/Makefile:37: recipe for target 'silentoldconfig' failed
make[6]: *** [silentoldconfig] Error 2
Makefile:543: recipe for target 'silentoldconfig' failed
make[5]: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
make[5]: Leaving directory '/openwrt/openwrt-d20220923-ub18-cools-m-ax1800-git-2/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60'
make[4]: *** [/openwrt/openwrt-d20220923-ub18-cools-m-ax1800-git-2/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60/.modules] Error 2
Makefile:23: recipe for target '/openwrt/openwrt-d20220923-ub18-cools-m-ax1800-git-2/build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60/.modules' failed
make[4]: Leaving directory '/openwrt/openwrt-d20220923-ub18-cools-m-ax1800-git-2/target/linux/ipq60xx'
make[3]: *** [compile] Error 2
Makefile:13: recipe for target 'compile' failed
重新制作内核配置文件中声卡SND_HDA_POWER_SAVE_DEFAULT选项后错误很多，持续修订如下：
echo '# CONFIG_IPQ_DWC3_QTI_EXTCON is not set' >>target/linux/ipq60xx/config-4.4
echo '# CONFIG_USB_QCOM_KS_BRIDGE is not set' >>target/linux/ipq60xx/config-4.4
echo 'CONFIG_NFSD_PNFS=y' >>target/linux/ipq60xx/config-4.4
echo '# CONFIG_CRYPTO_NO_ZERO_LEN_HASH is not set' >>target/linux/ipq60xx/config-4.4
echo '# CONFIG_CRYPTO_DISABLE_AES192_TEST is not set' >>target/linux/ipq60xx/config-4.4
继续编译错误日志如下：
  CC [M]  crypto/ablk_helper.o
crypto/ablk_helper.c: In function 'ablk_init':
crypto/ablk_helper.c:144:49: error: '%s' directive output may be truncated writing up to 63 bytes into a region of size 55 [-Werror=format-truncation=]
  snprintf(drv_name, sizeof(drv_name), "__driver-%s",
                                                 ^~
crypto/ablk_helper.c:144:2: note: 'snprintf' output between 10 and 73 bytes into a destination of size 64
  snprintf(drv_name, sizeof(drv_name), "__driver-%s",
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      crypto_tfm_alg_driver_name(tfm));
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[6]: *** [crypto/ablk_helper.o] Error 1
scripts/Makefile.build:343: recipe for target 'crypto/ablk_helper.o' failed
make[5]: *** [crypto] Error 2
Makefile:971: recipe for target 'crypto' failed

取消qmi选项后，错误日志如下：
sound/core/seq/seq_midi.c: In function 'snd_seq_midisynth_probe':
sound/core/seq/seq_midi.c:365:48: error: '%s' directive output may be truncated writing up to 79 bytes into a region of size 64 [-Werror=format-truncation=]
      snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
                                                ^~
sound/core/seq/seq_midi.c:365:47: note: directive argument in the range [0, 4294967294]
      snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
                                               ^~~~~~~
sound/core/seq/seq_midi.c:365:6: note: 'snprintf' output between 3 and 91 bytes into a destination of size 64
      snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sound/core/seq/seq_midi.c:367:48: error: '%s' directive output may be truncated writing up to 79 bytes into a region of size 64 [-Werror=format-truncation=]
      snprintf(port->name, sizeof(port->name), "%s", info->name);
                                                ^~
sound/core/seq/seq_midi.c:367:6: note: 'snprintf' output between 1 and 80 bytes into a destination of size 64
      snprintf(port->name, sizeof(port->name), "%s", info->name);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[8]: *** [sound/core/seq/seq_midi.o] Error 1
scripts/Makefile.build:337: recipe for target 'sound/core/seq/seq_midi.o' failed
make[7]: *** [sound/core/seq] Error 2
scripts/Makefile.build:573: recipe for target 'sound/core/seq' failed
make[6]: *** [sound/core] Error 2
scripts/Makefile.build:573: recipe for target 'sound/core' failed
make[5]: *** [sound] Error 2
Makefile:971: recipe for target 'sound' failed

**Comment by aiamadeus** [comment]
这就不修了，你在编译硬件不支持的东西。
