### ISSUE TITLE
正常编译配置下增加crypto-qcrypto模块出错

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/openwrt-gl-ax1800#36]
环境：
lsb_release -ra
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
。。。。。。。
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

正常编译配置下增加crypto-qcrypto模块出错：
diff 6000-d221002-OpenWrt-AX5-AX1800-3-luci.config .config
1908c1908
aa  < # CONFIG_PACKAGE_kmod-crypto-qcrypto is not set
bb  > CONFIG_PACKAGE_kmod-crypto-qcrypto=m

具体错误如下：
Makefile:1217: target '_clean_samples' given more than once in the same rule
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  HOSTCC  usr/gen_init_cpio
  GEN     usr/initramfs_data.cpio.gz
  AS      usr/initramfs_data.o
  LD      usr/built-in.o
  GZIP    kernel/config_data.gz
  CHK     kernel/config_data.h
  UPD     kernel/config_data.h
  CC      kernel/configs.o
  LD      kernel/built-in.o
  ASN.1   crypto/asymmetric_keys/x509-asn1.c
  CC      crypto/asymmetric_keys/x509-asn1.o
  ASN.1   crypto/asymmetric_keys/x509_akid-asn1.c
  CC      crypto/asymmetric_keys/x509_akid-asn1.o
  ASN.1   crypto/asymmetric_keys/x509_rsakey-asn1.c
  CC      crypto/asymmetric_keys/x509_rsakey-asn1.o
  CC      crypto/asymmetric_keys/x509_cert_parser.o
  LD      crypto/asymmetric_keys/x509_key_parser.o
  LD      crypto/asymmetric_keys/built-in.o
  LD      crypto/built-in.o
  LD      drivers/net/phy/qca_85xx/built-in.o
  LINK    vmlinux
  LD      vmlinux.o
  MODPOST vmlinux.o
WARNING: modpost: Found 1 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
  GEN     .version
  CHK     include/generated/compile.h
  KSYM    .tmp_kallsyms1.o
  KSYM    .tmp_kallsyms2.o
  LD      vmlinux
  SORTEX  vmlinux
  SYSMAP  System.map
  OBJCOPY arch/arm64/boot/Image
  Building modules, stage 2.
  MODPOST 740 modules
WARNING: drivers/usb/dwc3/dwc3-qcom: 'msm_ep_unconfig' exported twice. Previous export was in drivers/usb/dwc3/dwc3-of-simple.ko
WARNING: drivers/usb/dwc3/dwc3-qcom: 'msm_ep_config' exported twice. Previous export was in drivers/usb/dwc3/dwc3-of-simple.ko
WARNING: drivers/usb/dwc3/dwc3-qcom: 'msm_dwc3_reset_dbm_ep' exported twice. Previous export was in drivers/usb/dwc3/dwc3-of-simple.ko
WARNING: drivers/usb/dwc3/dwc3-qcom: 'msm_data_fifo_config' exported twice. Previous export was in drivers/usb/dwc3/dwc3-of-simple.ko
ERROR: "qce_hw_support" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_open" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_enable_clk" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_disable_clk" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_process_sha_req" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_aead_req" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_ablk_cipher_req" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_get_driver_stats" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_clear_driver_stats" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_close" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "qce_pm_table" [drivers/crypto/msm/qcrypto.ko] undefined!
ERROR: "compat_qcedev_ioctl" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_hw_support" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_open" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_close" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_disable_clk" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_enable_clk" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_process_sha_req" [drivers/crypto/msm/qcedev.ko] undefined!
ERROR: "qce_ablk_cipher_req" [drivers/crypto/msm/qcedev.ko] undefined!
make[6]: *** [__modpost] Error 1
scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[5]: *** [modules] Error 2
make[4]: *** build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60/.image] Error 2
make[3]: *** [install] Error 2
Makefile:1128: recipe for target 'modules' failed
make[5]: Leaving directory 'build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60'
Makefile:23: recipe for target 'build_dir/target-aarch64_cortex-a53_musl/linux-ipq60xx_generic/linux-4.4.60/.image' failed
make[4]: Leaving directory 'target/linux/ipq60xx'
Makefile:13: recipe for target 'install' failed
make[3]: Leaving directory 'target/linux'
time: target/linux/install#8.60#5.72#33.33
make[2]: *** [target/linux/install] Error 2
target/Makefile:23: recipe for target 'target/linux/install' failed

**Comment by paldier** [comment]
这里只支持ipq6k
