### ISSUE TITLE
正常编译配置下增加sound-core模块出错，不知是否能修复，不然和音频相关的全用不了，谢谢

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/openwrt-gl-ax1800#37]
环境：
lsb_release -ra
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.6 LTS
Release: 18.04
Codename: bionic

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
。。。。。。。
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

正常编译配置下增加sound-core模块 
diff 6000-d221002-OpenWrt-AX5-AX1800-3-luci.config .config
2431c2431,2441
aa < # CONFIG_PACKAGE_kmod-sound-core is not set

bb  > CONFIG_PACKAGE_kmod-sound-core=m

具体编译错误日志如下：
  CC [M]  sound/core/seq/seq_midi.o
sound/core/seq/seq_midi.c: In function 'snd_seq_midisynth_probe':
sound/core/seq/seq_midi.c:365:48: error: '%s' directive output may be truncated writing up to 79 bytes into a region of size 64 [-Werror=format-truncation=]
      snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
                                                ^~
sound/core/seq/seq_midi.c:365:47: note: directive argument in the range [0, 4294967294]
      snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
                                               ^~~~~~~
sound/core/seq/seq_midi.c:365:6: note: 'snprintf' output between 3 and 91 bytes into a destination of size 64
      snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sound/core/seq/seq_midi.c:367:48: error: '%s' directive output may be truncated writing up to 79 bytes into a region of size 64 [-Werror=format-truncation=]
      snprintf(port->name, sizeof(port->name), "%s", info->name);
                                                ^~
sound/core/seq/seq_midi.c:367:6: note: 'snprintf' output between 1 and 80 bytes into a destination of size 64
      snprintf(port->name, sizeof(port->name), "%s", info->name);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[8]: *** [sound/core/seq/seq_midi.o] Error 1
scripts/Makefile.build:337: recipe for target 'sound/core/seq/seq_midi.o' failed
make[7]: *** [sound/core/seq] Error 2
scripts/Makefile.build:573: recipe for target 'sound/core/seq' failed
make[6]: *** [sound/core] Error 2
scripts/Makefile.build:573: recipe for target 'sound/core' failed
make[5]: *** [sound] Error 2

**Comment by paldier** [comment]
路由芯片没有这功能
