### ISSUE TITLE
migrate to lede?

### ISSUE THREAD

**Issue by caffeinism** [coolsnowwolf/openwrt-gl-ax1800#45]
hello? I know this is not the main repository and not a good place to ask questions, but I just flashed the firmware from this repository, so I'm posting here.

I am a user of MR7350 and built the firmware by referring to this repository and lede repository. I initially tried building lede's latest commit and going through the factory.ubi file, but the stock firmware rejected it.

Later, when I built this repository, I found a factory.bin file, and I had the naive thought, "I can build this repository, install the old version, and then upgrade to lede's sysupgrade.bin!"

But well... I tried dozens of upgrades using luci and cli, but it was impossible. Common to both, the upgrade starts and the web and ssh shut down, but it just seems to reboot.

Looking at lede's commit, it seems that the upgrade process has changed a little as it has been changed to ubi. However, I don't know very much about this and I tried changing the file in /lib/upgrade/platform.sh to the lede version, but there was no change.

Is there any way for me?

**Comment by Vladdrako** [comment]
@caffeinism I'm in the same boat. Did you find a solution?

**Comment by caffeinism** [comment]
haha nope

**Comment by backslashxx** [comment]
@Vladdrako @caffeinism 
https://github.com/mrnuke/openwrt/tree/ipq6018-devel
