### ISSUE TITLE
有没有更新openss 到3.0的计划？

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/openwrt-gl-ax1800#58]
自己尝试了下更新openssl到3.0 发现各种问题，处理不了，参照lede 源码的更新也编译不过，看来只能等大佬出手了，不懂有没有更新openss 到3.0的计划？

**Comment by aiamadeus** [comment]
没有，本项目 fork 远比 star 多，而且 fork 项目的名声远好于本项目，本项目只收获一堆骂名，故不会再有任何更新。
