### ISSUE TITLE
需要流量镜像功能。需要如何做才能实现。

### ISSUE THREAD

**Issue by Gowa2017** [coolsnowwolf/openwrt-gl-ax1800#9]
尝试过  port mirroring 这个包 但这个依赖  tee。当前 1.3 固件似乎没这个包。

我看openwrt 新版本能直接在 switchcfg 里面设置镜像。

我们能做到么。

该怎么样进行编译或配置呢。

**Comment by coolsnowwolf** [comment]
需要 nss mirroring

**Comment by Gowa2017** [comment]
> 需要 nss mirroring

我改怎么做，直接编译此模块么。
